# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26dc8fb06e6719735c3d7eae767f0ab369c4667c355a41e43a072e82a4ce9e4eaafe5f01d6c3599339ead7834d37d835625c8aab19b98a298978c930759e286a

test:
  secret_key_base: 020e3e1c86a86d84353bdcbd7f847be97213a829701dce62c748cd2110e622cb2f5613a3fdc4ba3bfc06a9909fb8f880c2189537f140644b4d36dacd5bd23127

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
